src/ClinicaMedica.App/Controllers/EspecialidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClinicaMedica.App.Data;
using ClinicaMedica.App.ViewModels;
using ClinicaMedica.Business.Interfaces.Services;
using AutoMapper;
using ClinicaMedica.Business.Models;

namespace ClinicaMedica.App.Controllers
{
    public class EspecialidadeController : BaseController
    {

        private readonly IEspecialidadeService _especialidadeService;
        private readonly IMapper _mapper;

        public EspecialidadeController(IEspecialidadeService especialidadeService,
                                       IMapper mapper)
        {
            _especialidadeService = especialidadeService;
            _mapper = mapper;
        }
        
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<EspecialidadeViewModel>>(await _especialidadeService.ObterTodos()));
        }

        public async Task<IActionResult> Details(Guid id)
        {

            var especialidadeViewModel = await ObterEspecialidade(id);

            if (especialidadeViewModel == null)
            {
                return NotFound();
            }

            return View(especialidadeViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EspecialidadeViewModel especialidadeViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(especialidadeViewModel);
            }

            await _especialidadeService.Adicionar(_mapper.Map<Especialidade>(especialidadeViewModel));

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var especialidadeViewModel = await ObterEspecialidade(id);
            
            if (especialidadeViewModel == null)
            {
                return NotFound();
            }

            return View(especialidadeViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, EspecialidadeViewModel especialidadeViewModel)
        {
            if (id != especialidadeViewModel.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(especialidadeViewModel);
            }

            await _especialidadeService.Atualizar(_mapper.Map<Especialidade>(especialidadeViewModel));

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var especialidadeViewModel = await ObterEspecialidade(id);

            if (especialidadeViewModel == null)
            {
                return NotFound();
            }

            return View(especialidadeViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _especialidadeService.Remover(id);

            return RedirectToAction(nameof(Index));
        }

        private async Task<EspecialidadeViewModel> ObterEspecialidade(Guid id)
        {
            var especialidade = _mapper.Map<EspecialidadeViewModel>(await _especialidadeService.ObterEspecialidade(id));

            return especialidade;
        }
    }
}

src/ClinicaMedica.App/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClinicaMedica.App.Data;
using ClinicaMedica.App.ViewModels;
using ClinicaMedica.Business.Interfaces.Services;
using AutoMapper;
using ClinicaMedica.Business.Models;

namespace ClinicaMedica.App.Controllers
{
    public class MedicoController : Controller
    {
        private readonly IMedicoService _medicoService;
        private readonly IEspecialidadeService _especialidadeService;
        private readonly IMapper _mapper;

        public MedicoController(IMedicoService medicoService,
                                IEspecialidadeService especialidadeService,
                                IMapper mapper)
        {
            _medicoService = medicoService;
            _especialidadeService = especialidadeService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<MedicoViewModel>>(await _medicoService.ObterMedicosPorEspecialidades()));
        }

        public async Task<IActionResult> Details(Guid id)
        {

            var medicoViewModel = await ObterMedicoEspecialidade(id);

            if (medicoViewModel == null)
            {
                return NotFound();
            }

            return View(medicoViewModel);
        }

        public async Task<IActionResult> Create()
        {
            var medicoViewModel = await PopularEspecialidades(new MedicoViewModel());
            return View(medicoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MedicoViewModel medicoViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(medicoViewModel);
            }

            await _medicoService.Adicionar(_mapper.Map<Medico>(medicoViewModel));

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var medicoViewModel = await ObterMedico(id);

            medicoViewModel = await PopularEspecialidades(medicoViewModel);

            if (medicoViewModel == null)
            {
                return NotFound();
            }

            return View(medicoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, MedicoViewModel medicoViewModel)
        {
            if (id != medicoViewModel.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(medicoViewModel);
                
            }

            await _medicoService.Atualizar(_mapper.Map<Medico>(medicoViewModel));

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var medicoViewModel = await ObterMedicoEspecialidade(id);

            if (medicoViewModel == null)
            {
                return NotFound();
            }

            return View(medicoViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _medicoService.Remover(id);

            return RedirectToAction(nameof(Index));
        }

        private async Task<MedicoViewModel> ObterMedico(Guid id)
        {
            var medico = _mapper.Map<MedicoViewModel>(await _medicoService.ObterPorId(id));

            return medico;
        }

        private async Task<MedicoViewModel> ObterMedicoEspecialidade(Guid id)
        {
            var medico = _mapper.Map<MedicoViewModel>(await _medicoService.ObterMedicoEspecialidade(id));

            return medico;
        }

        private async Task<MedicoViewModel> PopularEspecialidades(MedicoViewModel medico)
        {
            medico.Especialidades = _mapper.Map <IEnumerable<EspecialidadeViewModel>> (await _especialidadeService.ObterTodos());
            return medico;
        }
    }
}

src/ClinicaMedica.App/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClinicaMedica.App.Data;
using ClinicaMedica.App.ViewModels;
using ClinicaMedica.Business.Interfaces.Services;
using AutoMapper;
using ClinicaMedica.Business.Models;

namespace ClinicaMedica.Application.Controllers
{
    public class PacienteController : Controller
    {
        private readonly IPacienteService _pacienteService;
        private readonly IMapper _mapper;

        public PacienteController(IPacienteService pacienteService, IMapper mapper)
        {
            _pacienteService = pacienteService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<PacienteViewModel>>(await _pacienteService.ObterPacientesPorEndereco()));
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var pacienteViewModel = await ObterPacienteEndereco(id);

            if (pacienteViewModel == null)
            {
                return NotFound();
            }

            return View(pacienteViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PacienteViewModel pacienteViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(pacienteViewModel);
            }

            var paciente = _mapper.Map<Paciente>(pacienteViewModel);

            await _pacienteService.Adicionar(paciente);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(Guid id)
        {

            var pacienteViewModel = await ObterPacienteEndereco(id);

            if (pacienteViewModel == null)
            {
                return NotFound();
            }

            return View(pacienteViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, PacienteViewModel pacienteViewModel)
        {
            if (id != pacienteViewModel.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(pacienteViewModel);
            }

            var paciente = _mapper.Map<Paciente>(pacienteViewModel);

            await _pacienteService.Atualizar(paciente);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var pacienteViewModel = await ObterPacienteEndereco(id);

            if (pacienteViewModel == null)
            {
                return NotFound();
            }

            return View(pacienteViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _pacienteService.Remover(id);

            return RedirectToAction(nameof(Index));
        }

        private async Task<PacienteViewModel> ObterPacienteEndereco(Guid id)
        {
            var paciente = _mapper.Map<PacienteViewModel>(await _pacienteService.ObterPacienteEndereco(id));
            return paciente;
        }
    }
}

src/ClinicaMedica.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClinicaMedica.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/fontawesome.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClinicaMedica.App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Especialidade" asp-action="Index">Especialidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medico" asp-action="Index">Médicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paciente" asp-action="Index">Pacientes</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ClinicaMedica.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/font-awesome/js/all.min.js"></script>
    <script src="~/font-awesome/js/fontawesome.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>